# oh-my-zsh
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="eastwood"
plugins=(git)
zstyle ':omz:update' mode disabled
[[ -f "$ZSH/oh-my-zsh.sh" ]] && source "$ZSH/oh-my-zsh.sh"

alias tmux="TERM=xterm-256color tmux"

# path
export PATH="$HOME/.local/bin:$PATH"

# >>> conda initialize >>>
__conda_setup="$('/opt/miniforge/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/opt/miniforge/etc/profile.d/conda.sh" ]; then
        . "/opt/miniforge/etc/profile.d/conda.sh"
    else
        export PATH="/opt/miniforge/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<
conda activate npu

# npu aliases (mirrors .bashrc set up by Dockerfile)
alias recompile='bash -c "$(head -n 1 compile_log.txt)"'
alias rebuildOV="python $HOME/.local/bin/build_openvino.py"
alias compareBlobs="$HOME/.local/bin/tensors_difference_helper.sh"
alias updateSimics="$HOME/.local/bin/update_simics_dir.sh"
alias setupPSS="$HOME/.local/bin/setup_pss_python_env.sh"
alias checkCopyrightHeaders='git diff --name-only develop...HEAD | xargs pre-commit run --hook-stage manual copyright-headers --file'
alias gotoOpenvinoBin='cd $OPENVINO_HOME/bin/intel64/RelWithDebInfo'
alias runLitTest="python $HOME/.local/bin/run_lit_test.py"
alias switchClang="sudo $HOME/.local/bin/switch_clang_version.sh"
alias tmuxWork="$HOME/.local/bin/tmux_work.sh"

# bash completions (npu_dev_completion and others)
autoload bashcompinit && bashcompinit
if [ -d ~/.bash_completion.d ]; then
    for file in ~/.bash_completion.d/*; do
        [ -f "$file" ] && source "$file"
    done
fi

# zoxide (cd alternative)
# eval "$(zoxide init zsh)"
